version: "3.8"

services:
  api:
    build: ./api
    entrypoint: sh ./entrypoint.sh
    environment:
      APP_PORT: 3000
    volumes:
      - ./api:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - redis
    networks:
      - rand-network

  redis:
    image: redis:6.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rand-network

networks:
  rand-network:
