version: "3.8"

services:
  api:
    build: ./api
    entrypoint: sh ./entrypoint.sh
    environment:
      APP_PORT: 3000
      MONGO_URL: root:root@localhost
    volumes:
      - ./api:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - redis
    networks:
      - rand-network
    depends_on:
      - mongodb

  redis:
    image: redis:6.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rand-network

  mongodb:
    image: mongo:5.0.0
    container_name: server-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - rand-network
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  rand-network:
